# ⚠️ WARNING: The previous key was exposed and should be revoked.
# Store your secrets securely here.

# Key for your internal Flask API
INTERNAL_API_KEY = "your-very-strong-and-secret-key"

# URL for your deployed Flask application
FLASK_API_URL = "http://127.0.0.1:5000" # Change to your production URL when deployed